
on: [push, pull_request]
name: CI

permissions: {}

jobs:
  test:
    name: Test (Go ${{ matrix.go-version }})

    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        go-version: ["1.25", "1.26"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: test
        run: |
          go install golang.org/x/lint/golint@latest &&
          go install github.com/go-bindata/go-bindata/...@latest &&
          go install honnef.co/go/tools/cmd/staticcheck@latest &&
          go generate &&
          make
