
on: [push, pull_request]
name: CI

permissions: {}

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - name: test
        run: |
          go install golang.org/x/lint/golint@latest &&
          go install github.com/go-bindata/go-bindata/...@latest &&
          go install honnef.co/go/tools/cmd/staticcheck@latest &&
          go generate &&
          make
