
on: [push, pull_request]
name: CI

permissions: {}

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - name: test
        run: |
          go install golang.org/x/lint/golint@latest &&
          go install github.com/go-bindata/go-bindata/...@latest &&
          go install honnef.co/go/tools/cmd/staticcheck@latest &&
          go generate &&
          make
